FROM golang:1.26 AS base

RUN git config --global --add safe.directory /go

ENV GOCACHE=/go/.go/cache GOPATH=/go/.go/path TZ=Europe/London

# Map between the working directories of dev and live
RUN ln -s /go /dis-authentication-stub
WORKDIR /dis-authentication-stub
