FROM golang:1.23.2-bullseye AS base

ENV GOCACHE=/go/.go/cache GOPATH=/go/.go/path TZ=Europe/London

RUN GOBIN=/bin go install github.com/cespare/reflex@v0.3.1

# Map between the working directories of dev and live
RUN ln -s /go /dis-authentication-stub
WORKDIR /dis-authentication-stub
