// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"crypto/rsa"
	"github.com/ONSdigital/dis-authentication-stub/models"
	"github.com/ONSdigital/dis-authentication-stub/static"
	"html/template"
	"sync"
)

// Ensure, that StoreMock does implement static.Store.
// If this is not the case, regenerate this file with moq.
var _ static.Store = &StoreMock{}

// StoreMock is a mock implementation of static.Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked static.Store
//		mockedStore := &StoreMock{
//			GetCollectionTemplateFunc: func() (*template.Template, error) {
//				panic("mock out the GetCollectionTemplate method")
//			},
//			GetDeleteTokenTemplateFunc: func() (*template.Template, error) {
//				panic("mock out the GetDeleteTokenTemplate method")
//			},
//			GetJWKsFunc: func() map[string]string {
//				panic("mock out the GetJWKs method")
//			},
//			GetKidsFunc: func() []string {
//				panic("mock out the GetKids method")
//			},
//			GetPrivateKeyFunc: func() *rsa.PrivateKey {
//				panic("mock out the GetPrivateKey method")
//			},
//			GetPublicKeyFunc: func() *rsa.PublicKey {
//				panic("mock out the GetPublicKey method")
//			},
//			GetUserFunc: func(email string) (*models.User, error) {
//				panic("mock out the GetUser method")
//			},
//			GetUserLoginTemplateFunc: func() (*template.Template, error) {
//				panic("mock out the GetUserLoginTemplate method")
//			},
//			GetUsersFunc: func() ([]models.User, error) {
//				panic("mock out the GetUsers method")
//			},
//		}
//
//		// use mockedStore in code that requires static.Store
//		// and then make assertions.
//
//	}
type StoreMock struct {
	// GetCollectionTemplateFunc mocks the GetCollectionTemplate method.
	GetCollectionTemplateFunc func() (*template.Template, error)

	// GetDeleteTokenTemplateFunc mocks the GetDeleteTokenTemplate method.
	GetDeleteTokenTemplateFunc func() (*template.Template, error)

	// GetJWKsFunc mocks the GetJWKs method.
	GetJWKsFunc func() map[string]string

	// GetKidsFunc mocks the GetKids method.
	GetKidsFunc func() []string

	// GetPrivateKeyFunc mocks the GetPrivateKey method.
	GetPrivateKeyFunc func() *rsa.PrivateKey

	// GetPublicKeyFunc mocks the GetPublicKey method.
	GetPublicKeyFunc func() *rsa.PublicKey

	// GetUserFunc mocks the GetUser method.
	GetUserFunc func(email string) (*models.User, error)

	// GetUserLoginTemplateFunc mocks the GetUserLoginTemplate method.
	GetUserLoginTemplateFunc func() (*template.Template, error)

	// GetUsersFunc mocks the GetUsers method.
	GetUsersFunc func() ([]models.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetCollectionTemplate holds details about calls to the GetCollectionTemplate method.
		GetCollectionTemplate []struct {
		}
		// GetDeleteTokenTemplate holds details about calls to the GetDeleteTokenTemplate method.
		GetDeleteTokenTemplate []struct {
		}
		// GetJWKs holds details about calls to the GetJWKs method.
		GetJWKs []struct {
		}
		// GetKids holds details about calls to the GetKids method.
		GetKids []struct {
		}
		// GetPrivateKey holds details about calls to the GetPrivateKey method.
		GetPrivateKey []struct {
		}
		// GetPublicKey holds details about calls to the GetPublicKey method.
		GetPublicKey []struct {
		}
		// GetUser holds details about calls to the GetUser method.
		GetUser []struct {
			// Email is the email argument value.
			Email string
		}
		// GetUserLoginTemplate holds details about calls to the GetUserLoginTemplate method.
		GetUserLoginTemplate []struct {
		}
		// GetUsers holds details about calls to the GetUsers method.
		GetUsers []struct {
		}
	}
	lockGetCollectionTemplate  sync.RWMutex
	lockGetDeleteTokenTemplate sync.RWMutex
	lockGetJWKs                sync.RWMutex
	lockGetKids                sync.RWMutex
	lockGetPrivateKey          sync.RWMutex
	lockGetPublicKey           sync.RWMutex
	lockGetUser                sync.RWMutex
	lockGetUserLoginTemplate   sync.RWMutex
	lockGetUsers               sync.RWMutex
}

// GetCollectionTemplate calls GetCollectionTemplateFunc.
func (mock *StoreMock) GetCollectionTemplate() (*template.Template, error) {
	if mock.GetCollectionTemplateFunc == nil {
		panic("StoreMock.GetCollectionTemplateFunc: method is nil but Store.GetCollectionTemplate was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetCollectionTemplate.Lock()
	mock.calls.GetCollectionTemplate = append(mock.calls.GetCollectionTemplate, callInfo)
	mock.lockGetCollectionTemplate.Unlock()
	return mock.GetCollectionTemplateFunc()
}

// GetCollectionTemplateCalls gets all the calls that were made to GetCollectionTemplate.
// Check the length with:
//
//	len(mockedStore.GetCollectionTemplateCalls())
func (mock *StoreMock) GetCollectionTemplateCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetCollectionTemplate.RLock()
	calls = mock.calls.GetCollectionTemplate
	mock.lockGetCollectionTemplate.RUnlock()
	return calls
}

// GetDeleteTokenTemplate calls GetDeleteTokenTemplateFunc.
func (mock *StoreMock) GetDeleteTokenTemplate() (*template.Template, error) {
	if mock.GetDeleteTokenTemplateFunc == nil {
		panic("StoreMock.GetDeleteTokenTemplateFunc: method is nil but Store.GetDeleteTokenTemplate was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetDeleteTokenTemplate.Lock()
	mock.calls.GetDeleteTokenTemplate = append(mock.calls.GetDeleteTokenTemplate, callInfo)
	mock.lockGetDeleteTokenTemplate.Unlock()
	return mock.GetDeleteTokenTemplateFunc()
}

// GetDeleteTokenTemplateCalls gets all the calls that were made to GetDeleteTokenTemplate.
// Check the length with:
//
//	len(mockedStore.GetDeleteTokenTemplateCalls())
func (mock *StoreMock) GetDeleteTokenTemplateCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetDeleteTokenTemplate.RLock()
	calls = mock.calls.GetDeleteTokenTemplate
	mock.lockGetDeleteTokenTemplate.RUnlock()
	return calls
}

// GetJWKs calls GetJWKsFunc.
func (mock *StoreMock) GetJWKs() map[string]string {
	if mock.GetJWKsFunc == nil {
		panic("StoreMock.GetJWKsFunc: method is nil but Store.GetJWKs was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetJWKs.Lock()
	mock.calls.GetJWKs = append(mock.calls.GetJWKs, callInfo)
	mock.lockGetJWKs.Unlock()
	return mock.GetJWKsFunc()
}

// GetJWKsCalls gets all the calls that were made to GetJWKs.
// Check the length with:
//
//	len(mockedStore.GetJWKsCalls())
func (mock *StoreMock) GetJWKsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetJWKs.RLock()
	calls = mock.calls.GetJWKs
	mock.lockGetJWKs.RUnlock()
	return calls
}

// GetKids calls GetKidsFunc.
func (mock *StoreMock) GetKids() []string {
	if mock.GetKidsFunc == nil {
		panic("StoreMock.GetKidsFunc: method is nil but Store.GetKids was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetKids.Lock()
	mock.calls.GetKids = append(mock.calls.GetKids, callInfo)
	mock.lockGetKids.Unlock()
	return mock.GetKidsFunc()
}

// GetKidsCalls gets all the calls that were made to GetKids.
// Check the length with:
//
//	len(mockedStore.GetKidsCalls())
func (mock *StoreMock) GetKidsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetKids.RLock()
	calls = mock.calls.GetKids
	mock.lockGetKids.RUnlock()
	return calls
}

// GetPrivateKey calls GetPrivateKeyFunc.
func (mock *StoreMock) GetPrivateKey() *rsa.PrivateKey {
	if mock.GetPrivateKeyFunc == nil {
		panic("StoreMock.GetPrivateKeyFunc: method is nil but Store.GetPrivateKey was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetPrivateKey.Lock()
	mock.calls.GetPrivateKey = append(mock.calls.GetPrivateKey, callInfo)
	mock.lockGetPrivateKey.Unlock()
	return mock.GetPrivateKeyFunc()
}

// GetPrivateKeyCalls gets all the calls that were made to GetPrivateKey.
// Check the length with:
//
//	len(mockedStore.GetPrivateKeyCalls())
func (mock *StoreMock) GetPrivateKeyCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetPrivateKey.RLock()
	calls = mock.calls.GetPrivateKey
	mock.lockGetPrivateKey.RUnlock()
	return calls
}

// GetPublicKey calls GetPublicKeyFunc.
func (mock *StoreMock) GetPublicKey() *rsa.PublicKey {
	if mock.GetPublicKeyFunc == nil {
		panic("StoreMock.GetPublicKeyFunc: method is nil but Store.GetPublicKey was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetPublicKey.Lock()
	mock.calls.GetPublicKey = append(mock.calls.GetPublicKey, callInfo)
	mock.lockGetPublicKey.Unlock()
	return mock.GetPublicKeyFunc()
}

// GetPublicKeyCalls gets all the calls that were made to GetPublicKey.
// Check the length with:
//
//	len(mockedStore.GetPublicKeyCalls())
func (mock *StoreMock) GetPublicKeyCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetPublicKey.RLock()
	calls = mock.calls.GetPublicKey
	mock.lockGetPublicKey.RUnlock()
	return calls
}

// GetUser calls GetUserFunc.
func (mock *StoreMock) GetUser(email string) (*models.User, error) {
	if mock.GetUserFunc == nil {
		panic("StoreMock.GetUserFunc: method is nil but Store.GetUser was just called")
	}
	callInfo := struct {
		Email string
	}{
		Email: email,
	}
	mock.lockGetUser.Lock()
	mock.calls.GetUser = append(mock.calls.GetUser, callInfo)
	mock.lockGetUser.Unlock()
	return mock.GetUserFunc(email)
}

// GetUserCalls gets all the calls that were made to GetUser.
// Check the length with:
//
//	len(mockedStore.GetUserCalls())
func (mock *StoreMock) GetUserCalls() []struct {
	Email string
} {
	var calls []struct {
		Email string
	}
	mock.lockGetUser.RLock()
	calls = mock.calls.GetUser
	mock.lockGetUser.RUnlock()
	return calls
}

// GetUserLoginTemplate calls GetUserLoginTemplateFunc.
func (mock *StoreMock) GetUserLoginTemplate() (*template.Template, error) {
	if mock.GetUserLoginTemplateFunc == nil {
		panic("StoreMock.GetUserLoginTemplateFunc: method is nil but Store.GetUserLoginTemplate was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetUserLoginTemplate.Lock()
	mock.calls.GetUserLoginTemplate = append(mock.calls.GetUserLoginTemplate, callInfo)
	mock.lockGetUserLoginTemplate.Unlock()
	return mock.GetUserLoginTemplateFunc()
}

// GetUserLoginTemplateCalls gets all the calls that were made to GetUserLoginTemplate.
// Check the length with:
//
//	len(mockedStore.GetUserLoginTemplateCalls())
func (mock *StoreMock) GetUserLoginTemplateCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetUserLoginTemplate.RLock()
	calls = mock.calls.GetUserLoginTemplate
	mock.lockGetUserLoginTemplate.RUnlock()
	return calls
}

// GetUsers calls GetUsersFunc.
func (mock *StoreMock) GetUsers() ([]models.User, error) {
	if mock.GetUsersFunc == nil {
		panic("StoreMock.GetUsersFunc: method is nil but Store.GetUsers was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetUsers.Lock()
	mock.calls.GetUsers = append(mock.calls.GetUsers, callInfo)
	mock.lockGetUsers.Unlock()
	return mock.GetUsersFunc()
}

// GetUsersCalls gets all the calls that were made to GetUsers.
// Check the length with:
//
//	len(mockedStore.GetUsersCalls())
func (mock *StoreMock) GetUsersCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetUsers.RLock()
	calls = mock.calls.GetUsers
	mock.lockGetUsers.RUnlock()
	return calls
}
